[custom]
target=clash

; --- 这里的名字必须和规则里的“自动选择”一字不差 ---
group=手动切换`select`自动选择`日本自动`香港自动`新加坡自动`美国自动`.*
group=自动选择`fallback`日本自动`香港自动`新加坡自动`美国自动`.*`http://www.gstatic.com/generate_204`1800

; --- 后台地区组 ---
group=日本自动`url-test`JP|日本|Japan`http://www.gstatic.com/generate_204`1800,,50
group=香港自动`url-test`HK|香港|Hong Kong`http://www.gstatic.com/generate_204`1800,,50
group=新加坡自动`url-test`SG|新加坡|Singapore`http://www.gstatic.com/generate_204`1800,,50
group=美国自动`url-test`US|美国|States`http://www.gstatic.com/generate_204`1800,,50

; --- 韩国台湾仅供手动选择 ---
group=韩国自动`url-test`KR|韩国|Korea`http://www.gstatic.com/generate_204`1800,,50
group=台湾自动`url-test`TW|台湾|Taiwan`http://www.gstatic.com/generate_204`1800,,50

; --- 引入规则文件 ---
ruleset=自动选择,https://raw.githubusercontent.com/aooner/Cloudflare/refs/heads/main/clash.ini
