[custom]
target=clash

; --- 注意：我在 .* 后面加了两个感叹号 !! ---
; 这两个感叹号的作用是：把抓到的节点全部塞进组里，并从主界面隐藏，只留两个大按钮。
group=手动切换`select`自动选择`日本自动`香港自动`新加坡自动`美国自动`.*!!
group=自动选择`fallback`日本自动`香港自动`新加坡自动`美国自动`.*!!`http://www.gstatic.com/generate_204`1800

; --- 地区组同理，也加上 !! 让节点不乱跑 ---
group=日本自动`url-test`JP|日本|Japan`http://www.gstatic.com/generate_204`1800,,50!!
group=香港自动`url-test`HK|香港|Hong Kong`http://www.gstatic.com/generate_204`1800,,50!!
group=新加坡自动`url-test`SG|新加坡|Singapore`http://www.gstatic.com/generate_204`1800,,50!!
group=美国自动`url-test`US|美国|States`http://www.gstatic.com/generate_204`1800,,50!!

; --- 强制控制：如果不属于任何组，直接在界面蒸发 ---
config_include_all_proxies=false

; --- 关联规则 ---
ruleset=自动选择,https://raw.githubusercontent.com/aooner/Cloudflare/refs/heads/main/clash.ini
ruleset=自动选择,[]FINAL
